eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#Default port for eureka server
server:
  port: 8888
spring:
  application:
    name: PAYMENT-PROVIDER-SERVICE